source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '8.0'

target ‘CaiBao’ do
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'

end
