source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target :'CB157' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end

target :'CB227' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end

target :'CB203' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end


target :'CB270' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end


target :'CB184' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end


target :'CB278' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end


target :'CB279' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end


target :'c66app13' do
    
    pod 'AFNetworking', '~> 3.1.0’
    pod 'MJRefresh'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'SDWebImage', '~>3.8'
    pod 'HyphenateLite'
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
end





